-- lua/mytheme/init.lua
-- Minimal, fast theme using your VS Code palette
local M = {}

local colors = {
  bg0 = '#141414',
  bg1 = '#1A1A1A',
  bg2 = '#2A2A2A',
  text = '#D6D6DD',
  strong = '#FFFFFF',
  muted = '#CCCCCC',
  primary = '#4C9DF3',
  cyan = '#88C0D0',
  teal = '#82D2CE',
  green = '#A3BE8C',
  yellow = '#EBCB8B',
  amber = '#F8C762',
  peach = '#EFB080',
  rose = '#BF616A',
  purple = '#AAA0FA',
  violet = '#AA9BF5',
  lavender = '#87C3FF',
  magenta = '#E394DC',
}

M.colors = colors

function M.init()
  vim.o.background = 'dark'
  vim.cmd 'highlight clear'
  vim.cmd 'syntax reset'
  vim.g.colors_name = 'cursordark'

  local hl = vim.api.nvim_set_hl
  local function set(group, opts)
    hl(0, group, opts)
  end

  local function hi(group, opts)
    local existing = vim.api.nvim_get_hl(0, { name = group, link = false })

    -- Do nothing if the group is already defined or linked
    if existing and next(existing) ~= nil then
      return
    end

    vim.api.nvim_set_hl(0, group, opts)
  end

  local g = vim.g

  g.cursordark_green_comments = g.cursordark_green_comments or 0
  g.cursordark_emph_types = g.cursordark_emph_types or 1
  g.cursordark_emph_funcs = g.cursordark_emph_funcs or 0
  g.cursordark_emph_idents = g.cursordark_emph_idents or 0
  g.cursordark_match_paren_style = g.cursordark_match_paren_style or 0
  g.cursordark_dim_punctuation = g.cursordark_dim_punctuation or 1

  -- Core highlights
  set('FlashLabel', { fg = colors.bg0, bg = colors.magenta, bold = true })
  set('Normal', { fg = colors.text, bg = colors.bg0 })
  set('Cursor', { fg = colors.bg0, bg = colors.strong })
  set('Empty', { fg = colors.strong, bg = 'NONE' })
  set('CursorLineNr', { fg = colors.strong, bg = colors.bg1 })
  set('EndOfBuffer', { fg = colors.bg0, bg = colors.bg0 })
  set('FoldColumn', { fg = colors.muted, bg = 'NONE' })
  set('Folded', { fg = colors.muted, bg = colors.bg2 })
  set('LineNr', { fg = colors.muted, bg = 'NONE' })
  set('MatchWord', { fg = colors.strong, bg = colors.primary })
  set('SignColumn', { fg = colors.muted, bg = 'NONE' })
  set('Signify', { fg = colors.primary, bg = 'NONE' })
  set('Ignore', { fg = colors.muted, bg = 'NONE' })
  set('Pmenu', { fg = colors.strong, bg = colors.bg2 })
  set('PmenuSbar', { fg = colors.bg2, bg = colors.bg2 })
  set('PmenuSel', { fg = colors.strong, bg = colors.primary })
  set('PmenuThumb', { fg = colors.bg2, bg = colors.bg2 })

  set('DiagnosticError', { fg = colors.rose, bg = 'NONE' })
  set('ErrorMsg', { fg = colors.rose, bg = 'NONE' })
  set('Error', { fg = colors.bg0, bg = colors.rose })

  set('DiagnosticHint', { fg = colors.yellow, bg = 'NONE' })

  set('ModeMsg', { fg = colors.muted, bg = 'NONE' })
  set('MoreMsg', { fg = colors.magenta, bg = 'NONE' })
  set('Question', { fg = colors.magenta, bg = 'NONE' })
  set('WarningMsg', { fg = colors.peach, bg = 'NONE' })
  set('ColorColumn', { fg = 'NONE', bg = colors.bg1 })
  set('CursorColumn', { fg = 'NONE', bg = colors.bg1 })
  set('CursorLine', { fg = 'NONE', bg = colors.bg1 })
  set('QuickFixLine', { fg = colors.strong, bg = colors.primary })
  set('StatusLine', { fg = colors.strong, bg = colors.bg2 })
  set('StatusLineNC', { fg = colors.muted, bg = colors.bg2 })
  set('VertSplit', { fg = colors.bg2, bg = colors.bg2 })
  set('WinSeparator', { fg = colors.bg2, bg = colors.bg0 })
  set('WildMenu', { fg = colors.strong, bg = colors.primary })
  set('IncSearch', { fg = colors.bg0, bg = colors.amber })
  set('CurSearch', { link = 'IncSearch' })
  set('Search', { fg = colors.strong, bg = colors.bg2 })
  set('Visual', { fg = 'NONE', bg = colors.bg2 })
  set('DiffAdd', { fg = colors.primary, bg = 'NONE' })
  set('DiffChange', { fg = colors.peach, bg = 'NONE' })
  set('DiffDelete', { fg = colors.rose, bg = colors.bg0 })
  set('DiffText', { fg = colors.peach, bg = colors.bg0 })
  set('Comment', { fg = colors.muted, bg = 'NONE' })
  set('PreProc', { fg = colors.peach, bg = 'NONE' })
  set('Special', { fg = colors.teal, bg = 'NONE' })
  set('Statement', { fg = colors.magenta, bg = 'NONE', bold = true })
  set('Character', { fg = colors.yellow, bg = 'NONE' })
  set('Directory', { fg = colors.lavender, bg = 'NONE' })
  set('Number', { fg = colors.yellow, bg = 'NONE' })
  set('SpecialComment', { fg = colors.muted, bg = 'NONE' })
  set('String', { fg = colors.rose, bg = 'NONE' })
  set('Title', { fg = colors.strong, bg = 'NONE', bold = true })
  set('Todo', { fg = colors.muted, bg = 'NONE', bold = true })
  set('Underlined', { fg = colors.lavender, bg = 'NONE', underline = true })
  set('SpellBad', { fg = 'NONE', bg = 'NONE', undercurl = true })
  set('SpellCap', { fg = 'NONE', bg = 'NONE', undercurl = true })
  set('SpellLocal', { fg = 'NONE', bg = 'NONE', undercurl = true })
  set('SpellRare', { fg = 'NONE', bg = 'NONE', undercurl = true })
  set('Terminal', { link = 'Normal' })
  set('TabLine', { link = 'StatusLineNC' })
  set('TabLineFill', { link = 'StatusLineNC' })
  set('TabLineSel', { link = 'StatusLine' })
  set('StatusLineTerm', { link = 'StatusLine' })
  set('StatusLineTermNC', { link = 'StatusLineNC' })
  set('VisualNOS', { link = 'Visual' })
  set('MsgArea', { link = 'Title' })
  set('diffAdded', { link = 'DiffAdd' })
  set('diffBDiffer', { link = 'WarningMsg' })
  set('diffChanged', { link = 'DiffChange' })
  set('diffCommon', { link = 'WarningMsg' })
  set('diffDiffer', { link = 'WarningMsg' })
  set('diffFile', { link = 'Directory' })
  set('diffIdentical', { link = 'WarningMsg' })
  set('diffIndexLine', { link = 'Number' })
  set('diffIsA', { link = 'WarningMsg' })
  set('diffNoEOL', { link = 'WarningMsg' })
  set('diffOnly', { link = 'WarningMsg' })
  set('diffRemoved', { link = 'DiffDelete' })
  set('Constant', { link = 'LibraryIdent' })
  set('NormalFloat', { bg = colors.bg2, fg = colors.text })
  set('FloatBorder', { link = 'NormalFloat' })
  set('Float', { link = 'Number' })
  set('StringDelimiter', { link = 'String' })
  set('Identifier', { link = 'LocalIdent' })
  set('Function', { link = 'LibraryFunc' })
  set('Boolean', { link = 'Statement' })
  set('Conditional', { link = 'Statement' })
  set('Exception', { link = 'Statement' })
  set('Include', { link = 'Statement' })
  set('Keyword', { link = 'Statement' })
  set('Label', { link = 'Statement' })
  set('Repeat', { link = 'Statement' })
  set('StorageClass', { link = 'Statement' })
  set('Structure', { link = 'Statement' })
  set('Define', { link = 'PreProc' })
  set('Macro', { link = 'PreProc' })
  set('PreCondit', { link = 'PreProc' })
  set('Type', { link = 'LibraryType' })
  set('Debug', { link = 'Special' })
  set('SpecialChar', { link = 'Special' })
  set('Tag', { link = 'Special' })
  set('Noise', { link = 'Delimiter' })
  set('Quote', { link = 'StringDelimiter' })
  set('Conceal', { link = 'Ignore' })
  set('NonText', { link = 'Ignore' })
  set('SpecialKey', { link = 'Ignore' })
  set('Whitespace', { link = 'Ignore' })
  set('ALEVirtualTextError', { link = 'ErrorMsg' })
  set('ALEVirtualTextWarning', { link = 'WarningMsg' })
  set('Searchlight', { link = 'IncSearch' })
  set('SignifySignAdd', { link = 'Signify' })
  set('SignifySignChange', { link = 'Signify' })
  set('SignifySignDelete', { link = 'Signify' })
  set('bibEntryKw', { link = 'LibraryIdent' })
  set('bibKey', { link = 'IdentifierDef' })
  set('bibType', { link = 'LibraryType' })
  set('cssAtRule', { link = 'Keyword' })
  set('cssAttr', { link = 'Keyword' })
  set('cssBraces', { link = 'cssNoise' })
  set('cssClassName', { link = 'LocalIdent' })
  set('cssColor', { link = 'cssAttr' })
  set('cssFunction', { link = 'Empty' })
  set('cssIdentifier', { link = 'LocalIdent' })
  set('cssProp', { link = 'LibraryType' })
  set('cssPseudoClassId', { link = 'LibraryIdent' })
  set('cssSelectorOp', { link = 'Operator' })
  set('gitcommitHeader', { link = 'Todo' })
  set('gitcommitOverflow', { link = 'Error' })
  set('gitcommitSummary', { link = 'Title' })
  set('goField', { link = 'LocalIdent' })
  set('goFunction', { link = 'FunctionDef' })
  set('goFunctionCall', { link = 'LibraryFunc' })
  set('goVarAssign', { link = 'LocalIdent' })
  set('goVarDefs', { link = 'IdentifierDef' })
  set('helpCommand', { link = 'helpExample' })
  set('helpExample', { link = 'markdownCode' })
  set('helpHeadline', { link = 'Title' })
  set('helpHyperTextEntry', { link = 'Comment' })
  set('helpHyperTextJump', { link = 'Underlined' })
  set('helpSectionDelim', { link = 'Ignore' })
  set('helpURL', { link = 'helpHyperTextJump' })
  set('helpVim', { link = 'Title' })
  set('htmlArg', { link = 'Special' })
  set('htmlEndTag', { link = 'Delimiter' })
  set('htmlLink', { link = 'Underlined' })
  set('htmlSpecialTagName', { link = 'htmlTagName' })
  set('htmlTag', { link = 'Delimiter' })
  set('htmlTagName', { link = 'Statement' })
  set('jinjaBlockName', { link = 'Typedef' })
  set('jinjaFilter', { link = 'LibraryFunc' })
  set('jinjaNumber', { link = 'Number' })
  set('jinjaOperator', { link = 'Operator' })
  set('jinjaRawDelim', { link = 'PreProc' })
  set('jinjaSpecial', { link = 'Keyword' })
  set('jinjaString', { link = 'String' })
  set('jinjaTagDelim', { link = 'Delimiter' })
  set('jinjaVarDelim', { link = 'Delimiter' })
  set('jsBuiltins', { link = 'LibraryFunc' })
  set('jsClassDefinition', { link = 'Typedef' })
  set('jsDomErrNo', { link = 'LibraryIdent' })
  set('jsDomNodeConsts', { link = 'LibraryIdent' })
  set('jsExceptions', { link = 'LibraryType' })
  set('jsFuncArgCommas', { link = 'jsNoise' })
  set('jsFuncName', { link = 'FunctionDef' })
  set('jsFunction', { link = 'jsStatement' })
  set('jsGlobalNodeObjects', { link = 'jsGlobalObjects' })
  set('jsGlobalObjects', { link = 'LibraryType' })
  set('jsObjectProp', { link = 'LocalIdent' })
  set('jsOperatorKeyword', { link = 'jsStatement' })
  set('jsThis', { link = 'jsStatement' })
  set('jsVariableDef', { link = 'IdentifierDef' })
  set('jsonKeyword', { link = 'jsonString' })
  set('jsonKeywordMatch', { link = 'Operator' })
  set('jsonQuote', { link = 'StringDelimiter' })
  set('lspdiagnosticssignerror', { link = 'ErrorMsg' })
  set('lspdiagnosticssignhint', { link = 'MoreMsg' })
  set('lspdiagnosticssigninformation', { link = 'ModeMsg' })
  set('lspdiagnosticssignwarning', { link = 'WarningMsg' })
  set('lspdiagnosticsunderlineerror', { undercurl = true, fg = colors.rose })
  set('lspdiagnosticsunderlineinformation', { undercurl = true, fg = colors.magenta })
  set('lspdiagnosticsunderlinewarning', { undercurl = true, fg = colors.peach })
  set('lspdiagnosticsvirtualtexterror', { link = 'ErrorMsg' })
  set('lspdiagnosticsvirtualtexthint', { link = 'MoreMsg' })
  set('lspdiagnosticsvirtualtextwarning', { link = 'WarningMsg' })
  set('lspdiagnosticsfloatingerror', { link = 'ErrorMsg' })
  set('lspdiagnosticsfloatingwarning', { link = 'WarningMsg' })
  set('lspdiagnosticsfloatinginformation', { link = 'ModeMsg' })
  set('lspdiagnosticsfloatinghint', { link = 'MoreMsg' })
  set('tsliteral', { link = 'Character' })
  set('tsannotation', { fg = colors.lavender })
  set('tsboolean', { link = 'Boolean' })
  set('tscharacter', { link = 'Character' })
  set('tscomment', { link = 'Comment' })
  set('tsconditional', { link = 'Conditional' })
  set('tsconstant', { link = 'Constant' })
  set('tsconstbuiltin', { link = 'Constant' })
  set('tsconstmacro', { link = 'Macro' })
  set('tserror', { fg = colors.bg1, bg = colors.strong, bold = true })
  set('tsexception', { link = 'Conditional' })
  set('tsfield', { link = 'Identifier' })
  set('tsfloat', { link = 'Float' })
  set('tsfunction', { link = 'Function' })
  set('tsfuncbuiltin', { link = 'Function' })
  set('tsfuncmacro', { link = 'Function' })
  set('tsinclude', { link = 'Include' })
  set('tskeyword', { link = 'Keyword' })
  set('tslabel', { link = 'Label' })
  set('tsmethod', { link = 'Function' })
  set('tsnamespace', { link = 'Conditional' })
  set('tsnumber', { link = 'Number' })
  set('tsoperator', { link = 'Operator' })
  set('tsparameterreference', { link = 'Constant' })
  set('tsproperty', { link = 'tsfield' })
  set('tspunctdelimiter', { link = 'Normal' })
  set('tspunctbracket', { link = 'Normal' })
  set('tspunctspecial', { link = 'Normal' })
  set('tsrepeat', { link = 'Conditional' })
  set('tsstring', { link = 'String' })
  set('tsstringregex', { link = 'Special' })
  set('tsstringescape', { link = 'Special' })
  set('tsstrong', { link = 'Normal' })
  set('tsconstructor', { link = 'Type' })
  set('tskeywordfunction', { link = 'Type' })
  set('tsparameter', { link = 'Label' })
  set('luaTSVariable', { link = 'Normal' })
  set('tsvariable', { link = 'Identifier' })
  set('tsvariablebuiltin', { link = 'Conditional' })
  set('tstag', { link = 'Label' })
  set('tstagdelimiter', { link = 'Label' })
  set('tstitle', { link = 'Special' })
  set('tstype', { link = 'Type' })
  set('tstypebuiltin', { link = 'Type' })
  set('tsemphasis', { link = 'Underlined' })
  set('rsForeignConst', { link = 'LibraryIdent' })
  set('rsForeignFunc', { link = 'LibraryFunc' })
  set('rsForeignType', { link = 'LibraryType' })
  set('rsFuncDef', { link = 'FunctionDef' })
  set('rsIdentDef', { link = 'IdentifierDef' })
  set('rsLibraryConst', { link = 'LibraryIdent' })
  set('rsLibraryFunc', { link = 'LibraryFunc' })
  set('rsLibraryType', { link = 'LibraryType' })
  set('rsLifetimeDef', { link = 'IdentifierDef' })
  set('rsSpecialLifetime', { link = 'LibraryIdent' })
  set('rsUserConst', { link = 'LocalIdent' })
  set('rsUserFunc', { link = 'LocalFunc' })
  set('rsUserLifetime', { link = 'LocalIdent' })
  set('rsUserMethod', { link = 'LibraryFunc' })
  set('rsUserType', { link = 'LocalType' })
  set('scssAttribute', { link = 'cssNoise' })
  set('scssInclude', { link = 'Keyword' })
  set('scssMixin', { link = 'Keyword' })
  set('scssMixinName', { link = 'LocalFunc' })
  set('scssMixinParams', { link = 'cssNoise' })
  set('scssSelectorName', { link = 'cssClassName' })
  set('scssVariableAssignment', { link = 'Operator' })
  set('scssVariableValue', { link = 'Operator' })
  set('swiftFuncDef', { link = 'FunctionDef' })
  set('swiftIdentDef', { link = 'IdentifierDef' })
  set('swiftLibraryFunc', { link = 'LibraryFunc' })
  set('swiftLibraryProp', { link = 'LibraryIdent' })
  set('swiftLibraryType', { link = 'LibraryType' })
  set('swiftUserFunc', { link = 'LocalFunc' })
  set('swiftUserProp', { link = 'LocalIdent' })
  set('swiftUserType', { link = 'LocalType' })
  set('typescriptArrayMethod', { link = 'LibraryFunc' })
  set('typescriptArrowFunc', { link = 'Operator' })
  set('typescriptAssign', { link = 'Operator' })
  set('typescriptBOM', { link = 'LibraryType' })
  set('typescriptBOMWindowCons', { link = 'LibraryType' })
  set('typescriptBOMWindowMethod', { link = 'LibraryFunc' })
  set('typescriptBOMWindowProp', { link = 'LibraryType' })
  set('typescriptBinaryOp', { link = 'Operator' })
  set('typescriptBraces', { link = 'Delimiter' })
  set('typescriptCall', { link = 'Empty' })
  set('typescriptClassHeritage', { link = 'Type' })
  set('typescriptClassName', { link = 'TypeDef' })
  set('typescriptDOMDocMethod', { link = 'LibraryFunc' })
  set('typescriptDOMDocProp', { link = 'LibraryIdent' })
  set('typescriptDOMEventCons', { link = 'LibraryType' })
  set('typescriptDOMEventMethod', { link = 'LibraryFunc' })
  set('typescriptDOMEventMethod', { link = 'LibraryFunc' })
  set('typescriptDOMEventProp', { link = 'LibraryIdent' })
  set('typescriptDOMEventTargetMethod', { link = 'LibraryFunc' })
  set('typescriptDOMNodeMethod', { link = 'LibraryFunc' })
  set('typescriptDOMStorageMethod', { link = 'LibraryIdent' })
  set('typescriptEndColons', { link = 'Delimiter' })
  set('typescriptExport', { link = 'Keyword' })
  set('typescriptFuncName', { link = 'FunctionDef' })
  set('typescriptFuncTypeArrow', { link = 'typescriptArrowFunc' })
  set('typescriptGlobal', { link = 'typescriptPredefinedType' })
  set('typescriptIdentifier', { link = 'Keyword' })
  set('typescriptInterfaceName', { link = 'Typedef' })
  set('typescriptMember', { link = 'LocalFunc' })
  set('typescriptObjectLabel', { link = 'LocalIdent' })
  set('typescriptOperator', { link = 'Keyword' })
  set('typescriptParens', { link = 'Delimiter' })
  set('typescriptPredefinedType', { link = 'LibraryType' })
  set('typescriptTypeAnnotation', { link = 'Delimiter' })
  set('typescriptTypeReference', { link = 'typescriptUserDefinedType' })
  set('typescriptUserDefinedType', { link = 'LocalType' })
  set('typescriptVariable', { link = 'Keyword' })
  set('typescriptVariableDeclaration', { link = 'IdentifierDef' })
  set('vimAutoCmdSfxList', { link = 'LibraryType' })
  set('vimAutoEventList', { link = 'LocalIdent' })
  set('vimCmdSep', { link = 'Special' })
  set('vimCommentTitle', { link = 'SpecialComment' })
  set('vimContinue', { link = 'Delimiter' })
  set('vimFuncName', { link = 'LibraryFunc' })
  set('vimFunction', { link = 'FunctionDef' })
  set('vimHighlight', { link = 'Statement' })
  set('vimMapModKey', { link = 'vimNotation' })
  set('vimNotation', { link = 'LibraryType' })
  set('vimOption', { link = 'LibraryIdent' })
  set('vimUserFunc', { link = 'LocalFunc' })
  set('markdownBoldDelimiter', { link = 'markdownDelimiter' })
  set('markdownBoldItalicDelimiter', { link = 'markdownDelimiter' })
  set('markdownCodeBlock', { link = 'markdownCode' })
  set('markdownCodeDelimiter', { link = 'markdownDelimiter' })
  set('markdownHeadingDelimiter', { link = 'markdownDelimiter' })
  set('markdownItalicDelimiter', { link = 'markdownDelimiter' })
  set('markdownLinkDelimiter', { link = 'markdownDelimiter' })
  set('markdownLinkText', { link = 'Empty' })
  set('markdownLinkTextDelimiter', { link = 'markdownDelimiter' })
  set('markdownListMarker', { link = 'markdownDelimiter' })
  set('markdownRule', { link = 'markdownDelimiter' })
  set('markdownUrl', { link = 'Underlined' })
  set('markdownDelimiter', { fg = colors.teal, bg = 'NONE' })
  set('markdownCode', { fg = colors.violet, bg = colors.bg2 })
  -- set('Comment', { fg = colors.green, bg = 'NONE' })
  set('SpecialComment', { fg = colors.green, bg = 'NONE' })
  set('Todo', { fg = colors.green, bg = 'NONE', bold = true })
  set('Typedef', { fg = colors.lavender, bg = 'NONE' })
  set('LocalType', { fg = colors.teal, bg = 'NONE' })
  set('LibraryType', { fg = colors.violet, bg = 'NONE' })
  set('Typedef', { fg = colors.primary, bg = 'NONE' })
  set('LocalType', { fg = colors.teal, bg = 'NONE' })
  set('LibraryType', { fg = colors.purple, bg = 'NONE' })
  set('FunctionDef', { fg = colors.lavender, bg = 'NONE' })
  set('LocalFunc', { fg = colors.teal, bg = 'NONE' })
  set('LibraryFunc', { fg = colors.violet, bg = 'NONE' })
  set('FunctionDef', { fg = colors.primary, bg = 'NONE' })
  set('LocalFunc', { fg = colors.teal, bg = 'NONE' })
  set('LibraryFunc', { fg = colors.purple, bg = 'NONE' })
  set('IdentifierDef', { fg = colors.lavender, bg = 'NONE' })
  set('LocalIdent', { fg = colors.teal, bg = 'NONE' })
  set('LibraryIdent', { fg = colors.violet, bg = 'NONE' })
  set('IdentifierDef', { fg = colors.primary, bg = 'NONE' })
  set('LocalIdent', { fg = colors.teal, bg = 'NONE' })
  set('LibraryIdent', { fg = colors.purple, bg = 'NONE' })
  set('MatchParen', { fg = colors.bg0, bg = colors.amber })
  set('MatchParen', { fg = colors.strong, bg = colors.primary })
  set('Delimiter', { fg = colors.muted, bg = 'NONE' })
  set('Operator', { fg = colors.muted, bg = 'NONE' })
  set('Delimiter', { fg = colors.strong, bg = 'NONE' })
  set('Operator', { fg = colors.strong, bg = 'NONE' })

  -- telescope
  set('TelescopeNormal', { bg = colors.bg1, fg = colors.muted })
  set('TelescopePromptNormal', { bg = colors.bg1, fg = colors.strong })
  set('TelescopeBorder', { bg = colors.bg1, fg = colors.muted })
  set('TelescopeMatching', { fg = colors.strong, bg = 'NONE', bold = true })
  set('TelescopePreviewMatch', { fg = colors.amber, bg = 'NONE', bold = true })
  set('TelescopePromptTitle', { fg = colors.strong, bg = 'NONE', bold = true })
  set('TelescopeResultsTitle', { link = 'TelescopePromptTitle' })
  set('TelescopePreviewTitle', { link = 'TelescopePromptTitle' })

  -- neotree
  set('NeoTreeNormal', { bg = colors.bg0 })
  set('NeoTreeNormalNC', { bg = colors.bg0 })
  set('NeoTreeEndOfBuffer', { fg = colors.bg0, bg = colors.bg0 })
  set('NeoTreeDirectoryName', { fg = colors.strong })
  set('NeoTreeDirectoryIcon', { fg = colors.muted })
  set('NeoTreeWinSeparator', { fg = colors.bg0, bg = colors.bg0 })
  set('NeoTreeFileName', { fg = colors.strong })
  set('NeoTreeFileNameOpened', { fg = colors.yellow, italic = true })
  set('NeoTreeCursorLine', { bg = colors.bg2 })
  set('NeoTreeGitModified', { fg = colors.amber })
  set('NeoTreeGitUntracked', { fg = colors.amber })
  set('NeoTreeIndentMarker', { fg = colors.muted })

  -- StatusLine highlights
  set('StatusLineNormal', { fg = colors.bg0, bg = colors.green, bold = true })
  set('StatusLineInsert', { fg = colors.bg0, bg = colors.primary, bold = true })
  set('StatusLineVisual', { fg = colors.bg0, bg = colors.purple, bold = true })
  set('StatusLineCommand', { fg = colors.bg0, bg = colors.peach, bold = true })

  -- idk what this stuff is
  if g.cursordark_green_comments == 1 then
    hi('Comment', { fg = colors.green })
    hi('SpecialComment', { fg = colors.green })
    hi('Todo', { fg = colors.green, bold = true })
  end

  if g.cursordark_emph_types == 1 then
    hi('Typedef', { fg = colors.lavender })
    hi('LocalType', { fg = colors.teal })
    hi('LibraryType', { fg = colors.violet })
  else
    hi('Typedef', { fg = colors.primary })
    hi('LocalType', { fg = colors.teal })
    hi('LibraryType', { fg = colors.purple })
  end

  if g.cursordark_emph_funcs == 1 then
    hi('FunctionDef', { fg = colors.lavender })
    hi('LocalFunc', { fg = colors.teal })
    hi('LibraryFunc', { fg = colors.violet })
  else
    hi('FunctionDef', { fg = colors.primary })
    hi('LocalFunc', { fg = colors.teal })
    hi('LibraryFunc', { fg = colors.purple })
  end

  if g.cursordark_emph_idents == 1 then
    hi('IdentifierDef', { fg = colors.lavender })
    hi('LocalIdent', { fg = colors.teal })
    hi('LibraryIdent', { fg = colors.violet })
  else
    hi('IdentifierDef', { fg = colors.primary })
    hi('LocalIdent', { fg = colors.teal })
    hi('LibraryIdent', { fg = colors.purple })
  end

  if g.cursordark_match_paren_style == 1 then
    hi('MatchParen', { fg = colors.bg0, bg = colors.amber })
  else
    hi('MatchParen', { fg = colors.strong, bg = colors.primary })
  end

  if g.cursordark_dim_punctuation == 1 then
    hi('Delimiter', { fg = colors.text })
    hi('Operator', { fg = colors.text })
  else
    hi('Delimiter', { fg = colors.strong })
    hi('Operator', { fg = colors.strong })
  end
end

return M
